# Assignment 3
# Aryan Tiwari

In [16]:
#Q1
import numpy as np
arr=np.arange(2,50,3)#Considering 50 Not included in the array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [10]:
#Q2
import numpy as np
a=[]
b=[]
print("For List 1: ")
for i in range(5):
    x=int(input("Enter an integer: "))
    a.append(x)
print("For List 2: ")
for i in range(5):
    x=int(input("Enter an integer: "))
    b.append(x)
print(a,type(a))
print(b,type(b))
a=np.array(a)
b=np.array(b)
print(a,type(a))
print(b,type(b))
print("Concatenated Array: ",np.concatenate((a,b)))
a=np.sort(a)
print("1st Array Sorted: ",a)
b=np.sort(b)
print("2nd Array Sorted: ",b)

For List 1: 
Enter an integer: 55
Enter an integer: 77
Enter an integer: 22
Enter an integer: 88
Enter an integer: 11
For List 2: 
Enter an integer: 45
Enter an integer: 25
Enter an integer: 95
Enter an integer: 35
Enter an integer: 65
[55, 77, 22, 88, 11] <class 'list'>
[45, 25, 95, 35, 65] <class 'list'>
[55 77 22 88 11] <class 'numpy.ndarray'>
[45 25 95 35 65] <class 'numpy.ndarray'>
Concatenated Array:  [55 77 22 88 11 45 25 95 35 65]
1st Array Sorted:  [11 22 55 77 88]
2nd Array Sorted:  [25 35 45 65 95]


In [13]:
#Q3
import numpy as np
arr=np.array([[1,2],[2,4],[5,7]])
print(arr)
print("Length of Array: ",len(arr))
print("Dimension of Array: ",arr.shape)

[[1 2]
 [2 4]
 [5 7]]
Length of Array:  3
Dimension of Array:  (3, 2)


In [20]:
#Q4
import numpy as np
#Method 1 - Using reshape
arr=np.arange(12)
print(arr)
print(arr.shape)
arr=arr.reshape(3,4)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [28]:
#Q4
import numpy as np
#Method 2 - Using np.newaxis
arr=np.arange(12)
print(arr)
print(arr.shape)
print()
arr1=arr[np.newaxis,:]
print(arr1)
print(arr1.shape)
print()
arr2=arr[:,np.newaxis]
print(arr2)
print(arr2.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(1, 12)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(12, 1)


In [32]:
#Q4
import numpy as np
#Method 2 - Using np.expand_dims
arr=np.arange(12)
print(arr)
print(arr.shape)
print()
arr1=np.expand_dims(arr, axis = 0) 
print(arr1)
print(arr1.shape)
print()
arr2=np.expand_dims(arr, axis = 1) 
print(arr2)
print(arr2.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(1, 12)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(12, 1)


In [10]:
#Q5
import numpy as np
a=np.arange(9).reshape(3,3)
b=np.ones(9).reshape(3,3)
print(a)
print(b)
print()
c=np.vstack((a,b))
print("Vertically stacked: \n",c)
print()
d=np.hstack((a,b))
print("Horizontally stacked: \n",d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Vertically stacked: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Horizontally stacked: 
 [[0. 1. 2. 1. 1. 1.]
 [3. 4. 5. 1. 1. 1.]
 [6. 7. 8. 1. 1. 1.]]


In [16]:
#Q6
import numpy as np
arr=np.array([[1,2,3,4],[4,3,5,6],[4,5,6,7],[7,8,8,9],[4,10,11,12]])
print(arr)
unique,count=np.unique(arr,return_counts=True)
print()
for i in range(len(unique)):
    print("Unique Element: ",unique[i])
    print("Element Count in Array: ",count[i])
    print()

[[ 1  2  3  4]
 [ 4  3  5  6]
 [ 4  5  6  7]
 [ 7  8  8  9]
 [ 4 10 11 12]]

Unique Element:  1
Element Count in Array:  1

Unique Element:  2
Element Count in Array:  1

Unique Element:  3
Element Count in Array:  2

Unique Element:  4
Element Count in Array:  4

Unique Element:  5
Element Count in Array:  2

Unique Element:  6
Element Count in Array:  2

Unique Element:  7
Element Count in Array:  2

Unique Element:  8
Element Count in Array:  2

Unique Element:  9
Element Count in Array:  1

Unique Element:  10
Element Count in Array:  1

Unique Element:  11
Element Count in Array:  1

Unique Element:  12
Element Count in Array:  1

